services:
  app:
    build: .
    ports:
      - "5000:5000" 
    volumes:
      - ./temp:/app/temp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PYTHONUNBUFFERED=1
      - OLLAMA_BASE_URL=http://host.docker.internal:11434